### ISSUE TITLE
"org.gradle.test-retry was unable to retry the following test methods, which is unexpected" is thrown when second try fails with initializationError

### ISSUE THREAD

**Issue by rovner** [gradle/test-retry-gradle-plugin#105]
Gradle build log
```
./gradlew test

> Task :test FAILED

ExampleTest > test() FAILED
    java.lang.AssertionError at ExampleTest.java:29

ExampleTest > initializationError FAILED
    java.lang.RuntimeException at ExampleTest.java:22

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues
     com.example.ExampleTest#test()


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

build.gradle
```
plugins {
    id 'java'
    id "org.gradle.test-retry" version "1.2.1"
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
}


//to simulate fail
task clarFlag() {
    doLast {
        file("build/flag").delete()
    }
}

test {
    useJUnitPlatform()
    retry {
        maxRetries = 3
        maxFailures = 20
        failOnPassedAfterRetry = true
    }
    finalizedBy clarFlag
}
```

Example test
```
package com.example;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

class ExampleTest {
    private final static Path flag = Paths.get("build/flag");

    @BeforeAll
    static void beforeAll() throws IOException {
        System.out.println("BEFORE");
        if (!flag.toFile().exists()) {
            Files.write(flag, "".getBytes(StandardCharsets.UTF_8));
        } else {
            throw new RuntimeException();
        }
    }

    @Test
    void test() {
        System.out.println("TEST");
        throw new AssertionError("TEST");
    }
}

```

**Comment by marcphilipp** [comment]
This behavior is actually somewhat expected. If a test that failed in a previous run isn't even started in a subsequent run, this error message is shown. You could make the case for retrying the entire test class in these cases in the third run but it's debatable.

@ldaley WDYT?

**Comment by rovner** [comment]
Hi @marcphilipp 

Here is my use case. Our usual end-to-end test looks like:
```
 @BeforeAll
    static void beforeAll() {
        //test environment setup, here some flakinnes may occur 
    }

    @Test
    void test() {
        //actual test
    }
```
Also we use `ignoreFailures = true` for our end to end to tests. So for me it is kind of not expected to break entire build when one test class failed to initialize.

**Comment by ldaley** [comment]
@marcphilipp we already have some encoded knowledge of how these class-level lifecycle methods fail. I think it would be better to in this case retry the test again, based on the understanding that the failure observed means we didn't get that far.

**Comment by broadcom-tony** [comment]
@marcphilipp or whomever, I am able to reproduce this error message as well but a different way.  I'm not sure if this should be a different issue or not but I am posting here because the error message is the same.

It appears to me that if your test method accepts parameters that can change between runs then RetryTestExcecutor will fail to remove that test from the `nonRetriedTests` TestNames map.  In our case the hashcode of the parameter will always change between runs therefore the TestDescriptorInternal.name will always change between retries.  https://github.com/gradle/test-retry-gradle-plugin/blob/master/plugin/src/main/java/org/gradle/testretry/internal/executer/RetryTestResultProcessor.java#L83 fails to remove the test from previousRoundFailedTests and results in RetryTestExecuter falling through to this condition on the second retry https://github.com/gradle/test-retry-gradle-plugin/blob/master/plugin/src/main/java/org/gradle/testretry/internal/executer/RetryTestExecuter.java#L99.

Here is the test structure note we are using TestNG (7.4.0):

`
@Test
 public void shouldNotBeAbleToCreateObjective(TestPersistenceContext context, RestSpec rest) {...}
`

I added to debug pint messages in the plugin to figure this out and here is what the parameters in the RetryTestResultProcessor.complete method look like:

Just before the remove is called (https://github.com/gradle/test-retry-gradle-plugin/blob/master/plugin/src/main/java/org/gradle/testretry/internal/executer/RetryTestResultProcessor.java#L83)

>TG: className: com.rallydev.webservice.rest.ObjectiveRestTest name: shouldBeAbleToCreateObjective[0](**com.rallydev.TestPersistenceContext@15c8b428, com.rallydev.webservice.rest.RestSpec@c59e4d0**)
TG: previousRoundFailedTests TestNames{map={com.rallydev.webservice.rest.ObjectiveRestTest=[shouldBeAbleToCreateObjective[0](**com.rallydev.TestPersistenceContext@7b888848, com.rallydev.webservice.rest.RestSpec@4992b4de)**]}}

Resulting error message happens on the second retry ... the first one works though:
* What went wrong:
Execution failed for task ':alm-webapp:integrationTest'.
> org.gradle.test-retry was unable to retry the following test methods, which is unexpected. Please file a bug report at https://github.com/gradle/test-retry-gradle-plugin/issues
     com.rallydev.webservice.rest.ObjectiveRestTest#shouldBeAbleToCreateObjective[0](com.rallydev.TestPersistenceContext@7b888848, com.rallydev.webservice.rest.RestSpec@4992b4de)


You can see the previousRoundFailedTests has the same test in there but with a different hashcode.  I can statically hard code the hash code in those classes and the plugin will retry properly but that seems a little hacky.  Not sure if this is expected, if you can thing of another way around this, or if this is actually a bug?

**Comment by ldaley** [comment]
@broadcom-tony this is more of an inherent limitation than bug. The test _name_ is the only valid identifier we have. Having names that aren't stable causes problems in a few different ways. 

I suggest using one of TestNG's mechanisms for controlling the test name, or implementing meaningful/stable toString() methods for your params.
