### ISSUE TITLE
[FEATURE] Filter retries with a specific test method

### ISSUE THREAD

**Issue by rocketraman** [gradle/test-retry-gradle-plugin#86]
The current filtering mechanism supports retries at the test class level, but it doesn't seem to support specifying the retry annotation at the test method level. It would be nice to annotate specific methods and then filter to those.

**Comment by ldaley** [comment]
@rocketraman I'm reluctant to do this as tracking the method declaration back from a reported test name is unreliable due to dynamic/modified test names, and this would lead to lots of cases where the annotation was silently ignored. At a class level is much more reliable.

I'm going to close based on this, but happy to keep discussing.

**Comment by rocketraman** [comment]
Why not just look for the annotation directly via reflection rather than trying to filter based on the method name?

**Comment by rocketraman** [comment]
I guess there is probably no easy way to do that easily and generically with multiple underlying test frameworks.

**Comment by ldaley** [comment]
> Why not just look for the annotation directly via reflection rather than trying to filter based on the method name?

We don't get told about failing test methods, just failing tests, and there's no guarantee there's a method with that name and there often isn't.
