### ISSUE TITLE
Fails to retry when MockitoJUnitRunner detects unnecessary stubbings

### ISSUE THREAD

**Issue by oehme** [gradle/test-retry-gradle-plugin#97]
The MockitoJUnitRunner adds methods of the form `MyTest#unnecessary Mockito stubbings`, which the test retry plugin tries to rerun. There seems to be no way to exclude individual methods from rerunning, which means I have no workaround.

**Comment by marcphilipp** [comment]
The only workaround I see would be to use `MockitoJUnitRunner.Silent` for the time being. A proper solution would be to allow specifying includes/excludes for methods in additions to classes on `Filter`. @ldaley WDYT?

**Comment by ldaley** [comment]
There's a little bit more to it than that. 

This is the first time we have run up against needing to exclude something because it _can't_ be retried. Up to now, we have had the assumption that effectively everything can be, or we have added specific support (e.g. failing lifecycle methods); the existing filter constructs are really for controlling which types of tests you want retried. While excludes would work in this case (if they had sufficient granularity) I'm not sure about solving this use case that way. Said another way, I'm not sure mixing “this cannot be retried” with “I do not want this retried” is the right thing to do.

A further nuance is that in some cases, it's not that such methods shouldn't be retried but that some other thing should be retried. For example, if a class level lifecycle method fails the right thing to do is retry the whole class. It's possible that this is also the case for this Mockito issue.

Stepping back even further though. What is Mockito doing here? What does such a failure actually mean? If it's related to an actual test (opposed to the test class), how does the user know which it is?

**Comment by oehme** [comment]
The MockitoJunitRunner creates a synthetic test method called `unnecessary Mockito stubbings`, which can't be retried because it doesn't exist. Why it doesn't just throw a class-level failure is beyond me. Retrying the whole class would work.

**Comment by marcphilipp** [comment]
> Retrying the whole class would work.

But retrying wouldn't make sense since the same check should fail again (unless the test is non-deterministic), wouldn't it?

**Comment by oehme** [comment]
> unless the test is non-deterministic

That's why we're retrying :)

**Comment by ldaley** [comment]
For now, let's just add support for retrying the class if a test with the name `unnecessary Mockito stubbings` fails.

@oehme would you mind contributing this?

**Comment by oehme** [comment]
> I still don't understand exactly what would cause this

You declare some stubbings. Your test fails before some of those stubbings actually got used. Mockito complains that you had unused stubbings by inserting a failed test method called `unnecessary Mockito stubbings`.

> @oehme would you mind contributing this?

Sure, will do

**Comment by ldaley** [comment]
> You declare some stubbings. Your test fails before some of those stubbings actually got used. 

Are stubbings a class or test level thing? What happens if two different tests have unused stubbings?

**Comment by oehme** [comment]
Both are supported - The runner waits till the end of the test class and then complains once about the unused stubbings.

I've just looked at the [implementation](https://github.com/mockito/mockito/blob/0ddbcb689e43f6a01f549c5efdd75defb39ebc14/src/main/java/org/mockito/internal/runners/StrictRunner.java#L45) and they only verify this if the test would otherwise be successful. So my assumption that this can happen due to an earlier flaky failure was wrong and @marcphilipp was right that this pretty much always means a coding error. So we should not retry the class, but instead not retry this synthetic method at all, as a retry won't fix this.

**Comment by ldaley** [comment]
IIRC, we don't make any provision for failing tests that we won't be able to retry. This means we have to decide whether the right behaviour is to retry other failures when such a failure is encountered or not.

Seems to me that without `--fail-fast` enabled, the right thing to do would be to continue with retrying other failures. I'm not entirely sure what we do about --fail-fast now in the retryable case actually.

**Comment by oehme** [comment]
> Seems to me that without --fail-fast enabled, the right thing to do would be to continue with retrying other failures.

Agreed

> I'm not entirely sure what we do about --fail-fast now in the retryable case actually.

I'll have a look what happens. Intuitively we should stop retrying as soon as the first test has definitively failed.

**Comment by ldaley** [comment]
@oehme where did we get to here?

**Comment by oehme** [comment]
I didn't get to this yet, will do so next.

**Comment by ldaley** [comment]
@oehme makes sense. Merged, thanks.
